pub mod block;
pub mod config;
pub mod error;
pub mod frontmatter;
pub mod git_sync;
pub mod index;
pub mod journal_date;
pub mod parser;
pub mod search;
pub mod vault;
pub mod watcher;

pub use block::{Block, Page};
pub use config::{Config, Theme};
pub use error::CoreError;
pub use git_sync::{SyncState, SyncStatus};
pub use index::{Backlink, Index, SyncOutcome};
pub use journal_date::JournalDate;
pub use search::{SearchHit, SearchIndex};
pub use vault::{PageSummary, Vault, VaultStats};
